version: "3.8"

services:
  web:
    build: .
    container_name: ci_php56
    ports:
      - "8081:80"
    volumes:
      - ./:/var/www/html
    extra_hosts:
      - "host.docker.internal:host-gateway"
