-- =====================================================
-- Migration: site_config labels, descriptions and missing keys
-- Date: 2026-09-01
-- Additive only. Does not DROP/ALTER columns (label + description already exist).
-- Re-runnable. Values are never overwritten.
-- The admin API also runs SiteConfigModel::sync_catalog() on first load.
-- =====================================================

UPDATE `site_config` SET `config_label` = 'Site title', `config_description` = 'Public name of the site. Used in the browser tab, admin chrome and Open Graph.', `config_type` = 'general' WHERE `config_name` = 'SITE_TITLE' AND (`config_label` IS NULL OR `config_label` = '' OR `config_label` = `config_name`);
UPDATE `site_config` SET `config_label` = 'Admin email', `config_description` = 'Contact address for site notices and RSS metadata.', `config_type` = 'general' WHERE `config_name` = 'SITE_ADMIN_EMAIL' AND (`config_label` IS NULL OR `config_label` = '' OR `config_label` = `config_name`);
UPDATE `site_config` SET `config_label` = 'Telephone', `config_description` = 'Public phone number shown by themes that render contact details.', `config_type` = 'general' WHERE `config_name` = 'SITE_TELEPHONE' AND (`config_label` IS NULL OR `config_label` = '' OR `config_label` = `config_name`);
UPDATE `site_config` SET `config_label` = 'Address', `config_description` = 'Public postal address shown by themes that render contact details.', `config_type` = 'general' WHERE `config_name` = 'SITE_ADDRESS' AND (`config_label` IS NULL OR `config_label` = '' OR `config_label` = `config_name`);
UPDATE `site_config` SET `config_label` = 'Map link', `config_description` = 'URL to a map of the public address (Google Maps or similar).', `config_type` = 'general' WHERE `config_name` = 'SITE_ADDRESS_LINK_MAP' AND (`config_label` IS NULL OR `config_label` = '' OR `config_label` = `config_name`);
UPDATE `site_config` SET `config_label` = 'Time zone', `config_description` = 'Offset used when formatting dates in the admin and public site.', `config_type` = 'general' WHERE `config_name` = 'SITE_TIME_ZONE' AND (`config_label` IS NULL OR `config_label` = '' OR `config_label` = `config_name`);
UPDATE `site_config` SET `config_label` = 'Date format', `config_description` = 'PHP date() pattern for calendar days (for example Y-m-d).', `config_type` = 'general' WHERE `config_name` = 'SITE_DATE_FORMAT' AND (`config_label` IS NULL OR `config_label` = '' OR `config_label` = `config_name`);
UPDATE `site_config` SET `config_label` = 'Time format', `config_description` = 'PHP date() pattern for hours (for example H:i).', `config_type` = 'general' WHERE `config_name` = 'SITE_TIME_FORMAT' AND (`config_label` IS NULL OR `config_label` = '' OR `config_label` = `config_name`);
UPDATE `site_config` SET `config_label` = 'List page size', `config_description` = 'Default number of items per page in admin lists.', `config_type` = 'general' WHERE `config_name` = 'SITE_LIST_MAX_ENTRY' AND (`config_label` IS NULL OR `config_label` = '' OR `config_label` = `config_name`);
UPDATE `site_config` SET `config_label` = 'Public list size', `config_description` = 'Default number of items per page on public listings.', `config_type` = 'general' WHERE `config_name` = 'SITE_LIST_PUBLIC' AND (`config_label` IS NULL OR `config_label` = '' OR `config_label` = `config_name`);
UPDATE `site_config` SET `config_label` = 'Home page ID', `config_description` = 'page_id served at the site root. 0 uses the default home template.', `config_type` = 'general' WHERE `config_name` = 'SITE_HOME_PAGE_ID' AND (`config_label` IS NULL OR `config_label` = '' OR `config_label` = `config_name`);
UPDATE `site_config` SET `config_label` = '404 page ID', `config_description` = 'page_id shown when a public URL is not found.', `config_type` = 'general' WHERE `config_name` = 'SITE_ERROR_404_PAGE_ID' AND (`config_label` IS NULL OR `config_label` = '' OR `config_label` = `config_name`);
UPDATE `site_config` SET `config_label` = 'Public blog', `config_description` = 'When Off, public blog routes and the RSS feed are disabled.', `config_type` = 'general' WHERE `config_name` = 'SITE_ACTIVE_BLOGS' AND (`config_label` IS NULL OR `config_label` = '' OR `config_label` = `config_name`);
UPDATE `site_config` SET `config_label` = 'Site description', `config_description` = 'Short summary for search results, RSS and social previews.', `config_type` = 'seo' WHERE `config_name` = 'SITE_DESCRIPTION' AND (`config_label` IS NULL OR `config_label` = '' OR `config_label` = `config_name`);
UPDATE `site_config` SET `config_label` = 'Site author', `config_description` = 'Author name used in metadata when a page does not set its own.', `config_type` = 'seo' WHERE `config_name` = 'SITE_AUTHOR' AND (`config_label` IS NULL OR `config_label` = '' OR `config_label` = `config_name`);
UPDATE `site_config` SET `config_label` = 'Site language', `config_description` = 'Primary language code of the public site (html lang and RSS).', `config_type` = 'seo' WHERE `config_name` = 'SITE_LANGUAGE' AND (`config_label` IS NULL OR `config_label` = '' OR `config_label` = `config_name`);
UPDATE `site_config` SET `config_label` = 'GitHub URL', `config_description` = 'Public GitHub profile or repository linked from the theme footer.', `config_type` = 'seo' WHERE `config_name` = 'SITE_LINK_GITHUB' AND (`config_label` IS NULL OR `config_label` = '' OR `config_label` = `config_name`);
UPDATE `site_config` SET `config_label` = 'Twitter URL', `config_description` = 'Public Twitter/X profile linked from the theme footer.', `config_type` = 'seo' WHERE `config_name` = 'SITE_LINK_TWITTER' AND (`config_label` IS NULL OR `config_label` = '' OR `config_label` = `config_name`);
UPDATE `site_config` SET `config_label` = 'Instagram URL', `config_description` = 'Public Instagram profile linked from the theme footer.', `config_type` = 'seo' WHERE `config_name` = 'SITE_LINK_INSTAGRAM' AND (`config_label` IS NULL OR `config_label` = '' OR `config_label` = `config_name`);
UPDATE `site_config` SET `config_label` = 'LinkedIn URL', `config_description` = 'Public LinkedIn profile linked from the theme footer.', `config_type` = 'seo' WHERE `config_name` = 'SITE_LINK_LINKEDIN' AND (`config_label` IS NULL OR `config_label` = '' OR `config_label` = `config_name`);
UPDATE `site_config` SET `config_label` = 'Active theme', `config_description` = 'Folder name under themes/ used to render the public site.', `config_type` = 'theme' WHERE `config_name` = 'THEME_PATH' AND (`config_label` IS NULL OR `config_label` = '' OR `config_label` = `config_name`);
UPDATE `site_config` SET `config_label` = 'Google Analytics', `config_description` = 'Injects the Analytics snippet on public pages when On.', `config_type` = 'integrations' WHERE `config_name` = 'ANALYTICS_ACTIVE' AND (`config_label` IS NULL OR `config_label` = '' OR `config_label` = `config_name`);
UPDATE `site_config` SET `config_label` = 'Analytics Measurement ID', `config_description` = 'GA4 Measurement ID (G-XXXXXXXX). Required when Analytics is on.', `config_type` = 'integrations' WHERE `config_name` = 'ANALYTICS_ID' AND (`config_label` IS NULL OR `config_label` = '' OR `config_label` = `config_name`);
UPDATE `site_config` SET `config_label` = 'Analytics head code', `config_description` = 'Optional extra snippet printed in <head> (gtag or Tag Manager).', `config_type` = 'integrations' WHERE `config_name` = 'ANALYTICS_CODE' AND (`config_label` IS NULL OR `config_label` = '' OR `config_label` = `config_name`);
UPDATE `site_config` SET `config_label` = 'Facebook Pixel', `config_description` = 'Injects the Meta Pixel snippet on public pages when On.', `config_type` = 'integrations' WHERE `config_name` = 'PIXEL_ACTIVE' AND (`config_label` IS NULL OR `config_label` = '' OR `config_label` = `config_name`);
UPDATE `site_config` SET `config_label` = 'Pixel ID or snippet', `config_description` = 'Meta Pixel ID or the full head snippet. Required when Pixel is on.', `config_type` = 'integrations' WHERE `config_name` = 'PIXEL_CODE' AND (`config_label` IS NULL OR `config_label` = '' OR `config_label` = `config_name`);
UPDATE `site_config` SET `config_label` = 'First-party visitor tracking', `config_description` = 'Records visits in this CMS (user_tracking). Independent from Google Analytics.', `config_type` = 'integrations' WHERE `config_name` = 'SITEM_TRACK_VISITORS' AND (`config_label` IS NULL OR `config_label` = '' OR `config_label` = `config_name`);
UPDATE `site_config` SET `config_label` = 'System activity log', `config_description` = 'Writes admin actions (create, update, delete) to the system log.', `config_type` = 'system' WHERE `config_name` = 'SYSTEM_LOGGER' AND (`config_label` IS NULL OR `config_label` = '' OR `config_label` = `config_name`);
UPDATE `site_config` SET `config_label` = 'API request log', `config_description` = 'Stores REST requests in api_logs. Useful for debugging integrations.', `config_type` = 'system' WHERE `config_name` = 'SYSTEM_API_LOGGER' AND (`config_label` IS NULL OR `config_label` = '' OR `config_label` = `config_name`);

-- Remap leftover types even when a custom label is already set
UPDATE `site_config` SET `config_type` = 'general' WHERE `config_name` IN ('SITE_TITLE','SITE_ADMIN_EMAIL','SITE_TELEPHONE','SITE_ADDRESS','SITE_ADDRESS_LINK_MAP','SITE_TIME_ZONE','SITE_DATE_FORMAT','SITE_TIME_FORMAT','SITE_LIST_MAX_ENTRY','SITE_LIST_PUBLIC','SITE_HOME_PAGE_ID','SITE_ERROR_404_PAGE_ID','SITE_ACTIVE_BLOGS') AND `config_type` IN ('seo','');
UPDATE `site_config` SET `config_type` = 'integrations' WHERE `config_name` IN ('ANALYTICS_ACTIVE','ANALYTICS_ID','ANALYTICS_CODE','PIXEL_ACTIVE','PIXEL_CODE','SITEM_TRACK_VISITORS') AND `config_type` IN ('analytics','pixel','logger','');
UPDATE `site_config` SET `config_type` = 'system' WHERE `config_name` IN ('SYSTEM_LOGGER','SYSTEM_API_LOGGER') AND `config_type` IN ('logger','');
UPDATE `site_config` SET `config_type` = 'internal', `readonly` = 1 WHERE `config_name` IN ('LAST_UPDATE_FILEMANAGER','LAST_AUTO_BACKUP','UPDATER_LAST_CHECK_UPDATE','UPDATER_LAST_CHECK_DATA');
