<?php
defined('BASEPATH') or exit('No direct script access allowed');

/*
| Closed catalog for the admin home. Widths are Materialize presets (3–9, 12).
| permission: SELECT_* / CREATE_* (string or list). Empty = always allowed.
| in_default false: available in the picker, not packed into the default home.
*/
$config['dashboard_widget_catalog'] = array(
    array(
        'id' => 'kpis',
        'component' => 'dashboardKpis',
        'permission' => 'SELECT_ANALYTICS',
        'w' => 12,
        'o' => 1,
        'lang' => 'dashboard_widget_kpis',
        'icon' => 'assessment',
    ),
    array(
        'id' => 'kpi_visitors',
        'component' => 'dashboardKpiCard',
        'permission' => 'SELECT_ANALYTICS',
        'w' => 3,
        'o' => 11,
        'in_default' => false,
        'lang' => 'dashboard_widget_kpi_visitors',
        'icon' => 'people',
    ),
    array(
        'id' => 'kpi_visits',
        'component' => 'dashboardKpiCard',
        'permission' => 'SELECT_ANALYTICS',
        'w' => 3,
        'o' => 12,
        'in_default' => false,
        'lang' => 'dashboard_widget_kpi_visits',
        'icon' => 'visibility',
    ),
    array(
        'id' => 'kpi_pages',
        'component' => 'dashboardKpiCard',
        'permission' => 'SELECT_ANALYTICS',
        'w' => 3,
        'o' => 13,
        'in_default' => false,
        'lang' => 'dashboard_widget_kpi_pages',
        'icon' => 'pages',
    ),
    array(
        'id' => 'kpi_bounce',
        'component' => 'dashboardKpiCard',
        'permission' => 'SELECT_ANALYTICS',
        'w' => 3,
        'o' => 14,
        'in_default' => false,
        'lang' => 'dashboard_widget_kpi_bounce',
        'icon' => 'exit_to_app',
    ),
    array(
        'id' => 'welcome',
        'component' => 'dashboardWelcome',
        'permission' => null,
        'w' => 12,
        'o' => 2,
        'lang' => 'dashboard_widget_welcome',
        'icon' => 'home',
    ),
    array(
        'id' => 'charts',
        'component' => 'dashboardCharts',
        'permission' => 'SELECT_ANALYTICS',
        'w' => 12,
        'o' => 3,
        'lang' => 'dashboard_widget_charts',
        'icon' => 'insert_chart',
    ),
    array(
        'id' => 'chart_visits',
        'component' => 'dashboardChartPanel',
        'permission' => 'SELECT_ANALYTICS',
        'w' => 6,
        'o' => 15,
        'in_default' => false,
        'lang' => 'dashboard_widget_chart_visits',
        'icon' => 'show_chart',
    ),
    array(
        'id' => 'chart_requests',
        'component' => 'dashboardChartPanel',
        'permission' => 'SELECT_ANALYTICS',
        'w' => 6,
        'o' => 16,
        'in_default' => false,
        'lang' => 'dashboard_widget_chart_requests',
        'icon' => 'bar_chart',
    ),
    array(
        'id' => 'chart_devices',
        'component' => 'dashboardChartPanel',
        'permission' => 'SELECT_ANALYTICS',
        'w' => 6,
        'o' => 17,
        'in_default' => false,
        'lang' => 'dashboard_widget_chart_devices',
        'icon' => 'devices',
    ),
    array(
        'id' => 'chart_urls',
        'component' => 'dashboardChartPanel',
        'permission' => 'SELECT_ANALYTICS',
        'w' => 6,
        'o' => 18,
        'in_default' => false,
        'lang' => 'dashboard_widget_chart_urls',
        'icon' => 'link',
    ),
    array(
        'id' => 'chart_top_pages',
        'component' => 'dashboardChartPanel',
        'permission' => 'SELECT_ANALYTICS',
        'w' => 6,
        'o' => 19,
        'in_default' => false,
        'lang' => 'dashboard_widget_chart_top_pages',
        'icon' => 'trending_up',
    ),
    array(
        'id' => 'chart_referrers',
        'component' => 'dashboardChartPanel',
        'permission' => 'SELECT_ANALYTICS',
        'w' => 6,
        'o' => 20,
        'in_default' => false,
        'lang' => 'dashboard_widget_chart_referrers',
        'icon' => 'share',
    ),
    array(
        'id' => 'users',
        'component' => 'usersCollection',
        'permission' => 'SELECT_USERS',
        'w' => 4,
        'o' => 4,
        'lang' => 'dashboard_widget_users',
        'icon' => 'people',
    ),
    array(
        'id' => 'files',
        'component' => 'fileExplorerCollection',
        'permission' => 'SELECT_FILES',
        'w' => 4,
        'o' => 5,
        'lang' => 'dashboard_widget_files',
        'icon' => 'folder',
    ),
    array(
        'id' => 'albums',
        'component' => 'albumesWidget',
        'permission' => 'SELECT_GALLERY',
        'w' => 4,
        'o' => 6,
        'lang' => 'dashboard_widget_albums',
        'icon' => 'photo_library',
    ),
    array(
        'id' => 'events',
        'component' => 'dashboardEvents',
        'permission' => 'SELECT_EVENTS',
        'w' => 6,
        'o' => 21,
        'in_default' => false,
        'lang' => 'dashboard_widget_events',
        'icon' => 'event',
    ),
    array(
        'id' => 'site_status',
        'component' => 'dashboardSiteStatus',
        'permission' => 'SELECT_CONFIG',
        'w' => 6,
        'o' => 22,
        'in_default' => false,
        'lang' => 'dashboard_widget_site_status',
        'icon' => 'info',
    ),
    array(
        'id' => 'quick_settings',
        'component' => 'dashboardQuickSettings',
        'permission' => 'SELECT_CONFIG',
        'w' => 6,
        'o' => 23,
        'in_default' => false,
        'lang' => 'dashboard_widget_quick_settings',
        'icon' => 'settings',
    ),
    array(
        'id' => 'collections',
        'component' => 'createContents',
        'permission' => array('SELECT_FORM_CUSTOMS', 'SELECT_CONTENT_DATA'),
        'permission_mode' => 'any',
        'w' => 12,
        'o' => 7,
        'lang' => 'dashboard_widget_collections',
        'icon' => 'view_module',
    ),
    array(
        'id' => 'creator',
        'component' => 'dashboardCreator',
        'permission' => array('CREATE_PAGE', 'CREATE_GALLERY', 'CREATE_CATEGORIE', 'CREATE_FRAGMENT'),
        'permission_mode' => 'any',
        'w' => 12,
        'o' => 8,
        'lang' => 'dashboard_widget_creator',
        'icon' => 'edit',
    ),
    array(
        'id' => 'drafts',
        'component' => 'dashboardDrafts',
        'permission' => 'SELECT_PAGES',
        'w' => 12,
        'o' => 9,
        'lang' => 'dashboard_widget_drafts',
        'icon' => 'description',
    ),
    array(
        'id' => 'timeline',
        'component' => 'dashboardTimeline',
        'permission' => 'SELECT_PAGES',
        'w' => 12,
        'o' => 10,
        'lang' => 'dashboard_widget_timeline',
        'icon' => 'history',
    ),
);
